#!/bin/bash
# 🐺 Elwood Timber v2.0
D="$HOME/.elwood" W="$HOME/Downloads" R="${ELWOOD_REPO:-phipigreywolf/claude-link}" B="${ELWOOD_BRANCH:-master}" POLL="${ELWOOD_POLL:-1}" H=""
BLOCKED='rm -rf /|mkfs|dd.*of=/dev|:\(\)\{|chmod -R 777 /|>/dev/sd|curl.*\|.*sh|wget.*\|.*sh'
log(){ echo "[$(date -Is)] [$2] $1" >> "$D/elwood.log"; }
notify(){ notify-send -u "${2:-normal}" "🐺 $1" "$3" 2>/dev/null ||:; }
validate(){ echo "$1" | grep -qE "$BLOCKED" && { log "BLOCKED: $1" "SECURITY"; return 1; }; return 0; }
run_cmd(){ local cmd="$1" desc="$2"; log "EXEC: $cmd" "CMD"; local out; out=$(timeout 60 bash -c "$cmd" 2>&1); local x=$?; log "EXIT: $x" "CMD"; echo "$out" > "$D/last_output"; echo "$out" | xclip -sel clip 2>/dev/null ||:; [ $x -eq 0 ] && notify "✓ $desc" low || notify "✗ $desc" normal; }
poll(){ local j; j=$(curl -sf --max-time 5 "https://raw.githubusercontent.com/$R/$B/command.json") || return; local nh=$(echo "$j"|md5sum|cut -d' ' -f1); [ "$nh" = "$H" ] && return; H="$nh"; local c=$(echo "$j"|jq -r '.command//.cmd//.script//empty'); [ -z "$c" ] && return; local d=$(echo "$j"|jq -r '.description//.desc//"GitHub"'); validate "$c" && { log "GITHUB: $d" "INFO"; run_cmd "$c" "$d"; }; }
watch_dl(){ inotifywait -mqe create,moved_to,close_write "$W" 2>/dev/null | while read -r _ _ F; do sleep 0.3; [ -f "$W/$F" ] || continue; if [[ "$F" =~ ^elwood(\([0-9]+\))?$ ]] && [[ ! "$F" == *angel* ]]; then log "UPGRADE: $F" "SYS"; sudo cp "$W/$F" /usr/local/bin/elwood && sudo chmod +x /usr/local/bin/elwood; rm -f "$W/$F"; continue; fi; if [[ "$F" =~ ^elwood-angel ]]; then log "INSTALL: $F" "SYS"; pkill -f "python.*elwood-angel" 2>/dev/null ||:; sudo cp "$W/$F" /usr/local/bin/elwood-angel && sudo chmod +x /usr/local/bin/elwood-angel; rm -f "$W/$F"; sleep 1; pgrep -f "python.*elwood-angel" >/dev/null || elwood-angel & continue; fi; if [[ "$F" =~ \.(claude|elwood)\.json$ ]]; then local c=$(jq -r '.command//.cmd//.script//empty' "$W/$F" 2>/dev/null); [ -z "$c" ] && continue; local d=$(jq -r '.description//.desc//"File"' "$W/$F"); validate "$c" && { log "FILE: $d" "INFO"; run_cmd "$c" "$d"; }; mv "$W/$F" "$D/done/$(date +%s)-$F" 2>/dev/null ||:; fi; done; }
start(){ mkdir -p "$D/done"; [ -f "$D/pid" ] && kill -0 $(cat "$D/pid") 2>/dev/null && echo "🐺 Running" && exit 0; log "STARTED" "SYS"; (while :; do poll; sleep "$POLL"; done) & watch_dl & echo $$ > "$D/pid"; echo "🐺 Elwood Timber"; pgrep -f "python.*elwood-angel" >/dev/null || [ ! -x /usr/local/bin/elwood-angel ] || elwood-angel & wait; }
stop(){ pkill -f "inotifywait.*Downloads" 2>/dev/null ||:; pkill -f "python.*elwood-angel" 2>/dev/null ||:; [ -f "$D/pid" ] && { kill $(cat "$D/pid") 2>/dev/null ||:; rm -f "$D/pid"; }; echo "🐺 Stopped"; }
case "${1:-}" in start) start & disown;; stop) stop;; restart) stop; sleep 1; exec "$0" start;; status) [ -f "$D/pid" ] && kill -0 $(cat "$D/pid") 2>/dev/null && echo "🐺 Running" || echo "🐺 Not running";; log) tail -50 "$D/elwood.log" 2>/dev/null;; angel) elwood-angel & echo "🐺 Angel";; test) run_cmd "echo 🐺 && date" "Test";; *) echo "🐺 elwood {start|stop|restart|status|log|angel|test}";; esac
